### ISSUE TITLE
Mock creation for `Symfony\Component\HttpFoundation\File\UploadedFile` throws Exception

### ISSUE THREAD

**Issue by floriansemm** [sebastianbergmann/phpunit-mock-objects#200]
PHPUnit throws the exception

`PHPUnit_Framework_MockObject_RuntimeException: unserialize(): Error at offset 37 of 38 bytes`

when creating a mock for the class `Symfony\Component\HttpFoundation\File\UploadedFile`

```
$fileMock = $this->getMock('Symfony\Component\HttpFoundation\File\UploadedFile', array(), array(), '', false);
```

PHP: v5.5.16
PHPUnit: v4.2.6
Mock objects: v2.2.1
Symfony: v2.5.4

With PHPUnit 3 I got the error described in #171.

**Comment by titolendable** [comment]
Hi @whatthejeff, I am having this exact same problem with php 5.5.19, everything seems to work fine with version 5.5.9. I tried to use the doctrine instantiator package, but got another unserialize error, here is my code:

$instantiator = new Instantiator();
$uploadedFile = $instantiator->instantiate('Symfony\Component\HttpFoundation\File\UploadedFile');

And now the error is:
Doctrine\Instantiator\Exception\UnexpectedValueException: Could not produce an instance of "Symfony\Component\HttpFoundation\File\UploadedFile" via un-serialization, since an error was triggered in file "/Users/titocosta/Projects/Lendable/vendor/doctrine/instantiator/src/Doctrine/Instantiator/Instantiator.php" at line "159"

Using version 1.0.4 of the doctrine instantiator library.

**Comment by titolendable** [comment]
I end up solving the problem calling the constructor, here is the way I mocked:

$this
            ->getMockBuilder('Symfony\Component\HttpFoundation\File\UploadedFile')
            ->enableOriginalConstructor()
            ->setConstructorArgs([tempnam(sys_get_temp_dir(), ''), 'dummy'])
            ->getMock();

**Comment by rene-s** [comment]
@titolendable Thanks a bunch :)
