### ISSUE TITLE
Namespaces in setMockClassName

### ISSUE THREAD

**Issue by ghost** [sebastianbergmann/phpunit-mock-objects#295]
Hello,

I came across #134 which was closed by the release of PHPUnit 5.0 and this issue still exists with PHPUnit 5.2.9.

Even though I can work-around with a "stub"-class (see below; btw: is that really a stub?), it'd be nice if I could simply define a namespace for a mock.

**Use case**, doesn't work

``` php
// src/AbstractFqcnNamedEvent.php
namespace MyApplication;

abstract class AbstractFqcnNamedEvent
{
    public function getNameFromFqcn()
    {
        return implode('.', explode('\\', static::class));
    }
}

// tests/AbstractFqcnNamedEventTest.php
namespace MyApplication\Tests;

class AbstractFqcnNamedEventTest extends \PHPUnit_Framework_TestCase
{
    public function testGetNameFromFqcn()
    {
        $event = $this->getMockForAbstractClass('AbstractFqcnNamedEvent', [], 'MyNamespace\\MyEvent');
        $this->assertEquals('MyNamespace.MyEvent', $event->getNameFromFqcn());
    }
}
```

**Workaround**

``` php
// tests/stubs/FqcnNamedEvent.php;
namespace MyApplication\Tests\stubs;

use MyApplication\AbstractFqcnNamedEvent;

class FqcnNamedEvent extends AbstractFqcnNamedEvent
{
}

// tests/AbstractFqcnNamedEventTest.php
namespace MyApplication\Tests;

class AbstractFqcnNamedEventTest extends \PHPUnit_Framework_TestCase
{
    public function testGetNameFromFqcn()
    {
        $event = new stubs\FqcnNamedEvent();
        $this->assertEquals('MyApplication.Tests.stubs.FqcnNamedEvent', $event->getNameFromFqcn());
    }
}
```

**Comment by damienflament** [comment]
I'm running the same issue. But for a different reason which does not involve any user code watching a class name.

It's just related to **argument type declaration**. I created a stub and give it to the tested function. But PHP 7 raise a _TypeError_ as the stub class is located in the root namespace.

Specifying the base classname
-------------------------------

The tested function declaration:
```php
namespace App\Composer;

use Composer\Script\Event;

class ScriptHandler
{
    public static function protectLibraries(Event $event)
    {
        // function definition
    }

    // remaining class definition ....
}
```

The test class:

```php
 namespace Test\Composer;

 use App\Composer\ScriptHandler;
 use PHPUnit\Framework\TestCase;

 class ScriptHandlerTest extends TestCase
 {
     private $event;

     public function createStub(string $className, array $methods)
     {
         return $this->getMockBuilder(\stdClass::class)
                     ->disableOriginalConstructor()
                     ->disableOriginalClone()
                     ->disableArgumentCloning()
                     ->disallowMockingUnknownTypes()
                     ->setMockClassName($className)
                     ->setMethods($methods)
                     ->getMock();
     }

     public function setUp()
     {
        $event = $this->createStub('Event', ['getIO', 'getComposer']);

        // more setup ...

        $this->event = $event;
     }

     public function testProtectLibraries()
     {
         ScriptHandler::protectLibraries($this->event);

         // remaining tests ...
     }
 }
```

The resulting error is:
> 1) Test\Composer\ScriptHandlerTest::testProtectLibraries
> TypeError: Argument 1 passed to App\Composer\ScriptHandler::exposeLibraries() must be an
> instance of **Composer\Script\Event**, instance of **Event** given

Using a namespace
--------------------

If I use the qualified classname :
```php
$event = $this->createStub('Composer\Script\Event', ['getIO', 'getComposer']);
```

The resulting error is:
> 1) Test\Composer\ScriptHandlerTest::testProtectLibraries
> ParseError: syntax error, unexpected '\' (T_NS_SEPARATOR), expecting '{'

The reason
-----------

After some debugging, I found that the code generated by the Mock Generator looks like this:
```php
class Composer\Script\Event extends stdClass implements PHPUnit_Framework_MockObject_MockObject
{
    // class definition ...
```
Instead of:
```php
namespace Composer\Script;

class Event extends stdClass implements PHPUnit_Framework_MockObject_MockObject
{
    // class definition ...
```

This is not surprising, as PHPUnit Mocks don't support namespaces. But **PHPUnit supports PHP 7.1** and **function arguments typing is now quite well supported in this language**.

---
**P.S**: I saw that PHPUnit Mock Object library is being refactored to use namespaces. Maybe
supporting namespace declaration for mock objects is already in the roadmap ?

**Comment by damienflament** [comment]
OK. After reading a little more the source code, I tried another solution:

The method _PHPUnit_Framework_MockObject_MockBuilder::**allowMockingUnknownTypes**()_ (or not calling _disallowMockingUnknownTypes_ on the builder as it seems to allow it by default) solves the issue.

I didn't use _setMockClassName_ anymore and **give the qualified classname to _getMockBuilder_**.

And it works !
