### ISSUE TITLE
Raise warning when trying to configure deprecated methods

### ISSUE THREAD

**Issue by sebastianbergmann** [sebastianbergmann/phpunit-mock-objects#307]
The changes introduced in https://github.com/sebastianbergmann/phpunit-mock-objects/pull/284 only lead to a "silent warning" being triggered when deprecated methods are stubbed or mocked:

``` php
<?php
class Example
{
    /**
     * @deprecated foo
     */
    public function doSomething()
    {
    }
}

class ExampleTest extends PHPUnit_Framework_TestCase
{
    public function testOne()
    {
        $stub = $this->createMock(Example::class);

        $stub->method('doSomething')
             ->willReturn('foo');
    }
}
```

```
$ phpunit ExampleTest
PHPUnit 5.4-g7735f76 by Sebastian Bergmann and contributors.

.                                                                   1 / 1 (100%)

Time: 24 ms, Memory: 4.00MB

OK (1 test, 0 assertions)
```

I think it would be better if this resulted in a `PHPUnit_Framework_MockObject_Exception` that is interpreted by PHPUnit to mark the test in question with a warning.

Thoughts? @nicolas-grekas

**Comment by stof** [comment]
Triggering an exception means that this will prevent the test from running. This means it would not be a deprecation anymore, as a deprecated API is meant to continue to work like previously.

This is the reason why Symfony started to use silenced warnings to report deprecations rather than non-silenced ones. The Symfony 2.7.0 release was not silencing them, and it broke CI for most libraries using Symfony components, while there was still time to update.

We rely on http://symfony.com/doc/current/components/phpunit_bridge.html to make the deprecation reporting opt-in.

**Comment by nicolas-grekas** [comment]
The issue with a exception is that it would break the code flow. Running deprecated code is perfectly fine until you decide to prepare the migration to the next version of your deps. Thus, the code flow should not change. That's why we choose the silenced deprecations.

**Comment by bradynpoulsen** [comment]
What if you threw the exception when the coverage strictness is enabled and the test doesn't specify `@covers ::doSomething()`. It could then be silenced by something like `@usesDeprecated doSomething` or `@deprecated doSomething` to signal it acknowledges the method is deprecated, but continue anyways.
